//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMERKATEGORIA
    {
        public int ID { get; set; }
        public Nullable<int> Категория { get; set; }
        public Nullable<int> Количество_комнат { get; set; }
        public Nullable<int> Количество_мест { get; set; }
        public string Стоимость { get; set; }
    
        public virtual Номера Номера { get; set; }
    }
}
