//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Дополнительное_обслуживание
    {
        public int ID { get; set; }
        public Nullable<int> ID_Обслуживания { get; set; }
        public Nullable<int> ID_Клиента { get; set; }
        public Nullable<System.DateTime> Дата_обслуживания { get; set; }
        public string Стоимость_обслуживания { get; set; }
    
        public virtual Виды_обслуживания Виды_обслуживания { get; set; }
        public virtual Клиенты Клиенты { get; set; }
    }
}
