//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сводная_таблица
    {
        public int ID_Записи { get; set; }
        public Nullable<int> ID_Номера { get; set; }
        public Nullable<int> ID_Клиента { get; set; }
        public Nullable<System.DateTime> Дата_засиления { get; set; }
        public Nullable<System.DateTime> Дата_высиления { get; set; }
        public string Комиентарий { get; set; }
        public Nullable<int> Обслуживание { get; set; }
    
        public virtual Дополнительное_обслуживание Дополнительное_обслуживание { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual Номера Номера { get; set; }
    }
}
